name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-11
    
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Build and test at macos
      run: |
        cd EssentialFeed
        xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme CI_macOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    
    - name: Build and test at iPhone 11 Pro
      run: |
        cd EssentialFeed
        xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme CI_iOS -destination "platform=iOS Simulator,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
